#!/bin/bash

COUNTDOWN_PARAM="$@"

ONLY_HOURS=$((4*60*60))
ONLY_MINUTES=$((1*60))

NO_SLEEP=${NO_SLEEP}

if [ -z "$COUNTDOWN_PARAM" ]
then
    echo "Must provide a countdown parameter..." >&2
#    exit 1
fi

param_get_scalar ()
{
    local param="$1"
    echo $(sed 's/^\([0-9]\+\)\s*\([a-zA-Z]\+\)$/\1/g' <<< ${param})
}

param_get_unit ()
{
    local param="$1"
    echo $(sed 's/^\([0-9]\+\)\s*\([a-zA-Z]\+\)$/\2/g' <<< ${param})
}

param_to_seconds ()
{
    local total_seconds=0
    local multiplier=1
    local args=( $@ )

    for arg in ${args[*]}
    do
        multiplier=0

        local unit=$(param_get_unit ${arg})
        local scalar=$(param_get_scalar ${arg})

        if [ "${unit:0:1}" == "s" ]
        then
            multiplier=1
        elif [ "${unit:0:1}" == "m" ]
        then
            multiplier=60
        elif [ "${unit:0:1}" == "h" ]
        then
            multiplier=$((60*60))
        elif [ "${unit:0:1}" == "d" ]
        then
            multiplier=$((24*60*60))
        fi

        if [[ $multiplier -gt 0 ]]
        then
            let total_seconds+=$((${scalar}*${multiplier}))
        fi
    done
    
    echo $total_seconds
}

show_loop_countdown ()
{
    local countdown_param="$@"
    local wait_seconds=$(param_to_seconds ${countdown_param})
    local first_run=y

    while [[ $wait_seconds -gt 0 ]]
    do
        left_hrs=$((${wait_seconds}/(60*60)))
        left_min=$(((${wait_seconds}-(${left_hrs}*60*60))/(60)))
        left_sec=$(((${wait_seconds}-(${left_hrs}*60*60))%(60)))

        if [[ $wait_seconds -ge ${ONLY_HOURS} ]]
        then
            if [[ ${left_min} -eq 0 ]] || [ -n "$first_run" ]
            then
                first_run=
                echo "${left_hrs}h, ${left_min}m, ${left_sec}s; remaing..."
            fi
        elif [[ $wait_seconds -ge ${ONLY_MINUTES} ]]
        then
            if [[ ${left_sec} -eq 0 ]] || [ -n "$first_run" ]
            then
                first_run=
                echo "${left_min}m, ${left_sec}s; remaing..."
            fi
        else
            echo "${left_hrs}h, ${left_min}m, ${left_sec}s; remaing..."
        fi

        sleep 1
        let wait_seconds-=1
    done
}

show_loop_countdown $@
