#!/bin/bash

SCRIPT_PATH=$(readlink -m "$0")
SCRIPT_NAME=$(basename "$SCRIPT_PATH")

CWD=$(pwd)

while [ -n "$1" ]
do
    py_class=$1
    py_class_path=$(tr '.' '/' <<< ${py_class})
    py_module_dir=$(dirname "${py_class_path}")
    
    echo -e "\n# ${py_class}"
    mkdir -pv "$py_module_dir"
    touch "${py_module_dir}/__init__.py" "${py_class_path}.py"
    shift
done
