#!/bin/bash

changedDays=${1:-1}

changedFiles=(`find ~/.purple/logs -type f -mtime -${changedDays} -print | egrep -v "/\.system/" | sort`)

echo "Found ${#changedFiles[*]} changed files..."
sleep 1

tail -n 15 ${changedFiles[*]} | sed 's/<[^>]*>//g' | less

